name: Sayhello

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Donwload your code
        uses: actions/checkout@v2

      - name: Say Something
        run: echo "Hellow World"
    
