name: Sayhello

on:
  push:
    branches:
      - develop
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Donwload your code
        uses: actions/checkout@v2

      - name: Say Something
        run: echo "Hellow World"
  
  hellos-branches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Donwload your code
      uses: actions/checkout@v2
  
    - name: Verify branch develops
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: echo "Hello Develop"
  
    - name: verify branch main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "Hello main"
